#!/bin/bash
set -e

case "$1" in
    remove|upgrade|deconfigure)
        # Note: cctv-viewer is a user service, users should stop it with:
        #   systemctl --user stop cctv-viewer.service
        # We'll try to kill any running instances
        pkill -f '/usr/bin/cctv-viewer' || true
        ;;
esac

#DEBHELPER#

exit 0
