[General]
editMode=false

[LayoutsCollection]
currentIndex=0
models="[{\"Viewport\":[{\"avOptions\":\"\",\"url\":\"rtsp://127.0.0.1:8554/fido_cctv?rtsp_transport=tcp\"},{\"avOptions\":\"\",\"url\":\"rtsp://127.0.0.1:8554/boxer_cctv?rtsp_transport=tcp\"},{\"avOptions\":\"\",\"url\":\"rtsp://127.0.0.1:8554/buster_cctv?rtsp_transport=tcp\"},{\"avOptions\":\"\",\"url\":\"\"},{\"avOptions\":\"\",\"url\":\"\"},{\"avOptions\":\"\",\"url\":\"\"}],\"fullScreenIndex\":-1,\"mergedCells\":[],\"size\":{\"height\":2,\"width\":3}},{\"Viewport\":[{\"avOptions\":\"\",\"url\":\"rtsp://127.0.0.1:8554/fido_cctv?rtsp_transport=tcp\"},{\"avOptions\":\"\",\"url\":\"rtsp://127.0.0.1:8554/boxer_cctv?rtsp_transport=tcp\"},{\"avOptions\":\"\",\"url\":\"rtsp://127.0.0.1:8554/buster_cctv?rtsp_transport=tcp\"},{\"avOptions\":\"\",\"url\":\"rtsp://127.0.0.1:8554/boxer_cctv?rtsp_transport=tcp\"},{\"avOptions\":\"\",\"url\":\"\"},{\"avOptions\":\"\",\"url\":\"\"}],\"fullScreenIndex\":-1,\"mergedCells\":[],\"size\":{\"height\":2,\"width\":3}}]"
presetInterval=10000

[RootWindow]
editMode=false
persistentStreams=true
showSideBar=true
x=0
y=0

[SideBar]
aspectRatios="[\"4:3\",\"16:9\",\"32:27\"]"

[Viewport]
muted=true
