name: cctv-viewer
version: '0.1.9+git'
license: GPL-3.0
icon: images/cctv-viewer.svg
title: CCTV Viewer
summary: Viewer and mounter video streams
description: |
  CCTV Viewer - a simple application for simultaneously viewing multiple
  video streams. Designed for high performance and low latency.
  Based on ffmpeg.
website: https://cctv-viewer.org
contact: mailto:me@vragam.net
issues: https://github.com/iEvgeny/cctv-viewer/issues
source-code: https://github.com/iEvgeny/cctv-viewer

grade: stable
confinement: strict
base: core24
compression: lzo

platforms:
  amd64:
  arm64:
  armhf:
  ppc64el:

environment:
  ARCH_TRIPLET: $CRAFT_ARCH_TRIPLET_BUILD_FOR

plugs:
  gpu-2404:
    interface: content
    target: $SNAP/gpu-2404
    default-provider: mesa-2404
  # Support for common GTK themes
  # https://forum.snapcraft.io/t/how-to-use-the-system-gtk-theme-via-the-gtk-common-themes-snap/6235
  gtk-3-themes:
    interface: content
    target: $SNAP/share/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/share/icons
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/share/sounds
    default-provider: gtk-common-themes

layout:
  /usr/share/X11/XErrorDB:
    symlink: $SNAP/gpu-2404/X11/XErrorDB
  /usr/share/X11/locale:
    symlink: $SNAP/gpu-2404/X11/locale

apps:
  cctv-viewer:
    command-chain:
      - bin/gpu-2404-wrapper
      - bin/desktop-launch
    command: usr/bin/cctv-viewer
    desktop: usr/share/applications/cctv-viewer.desktop
    plugs:
      - audio-playback
      - camera
      - desktop
      - desktop-legacy
      - gsettings
      - home
      - network
      - opengl
      - removable-media
      - screen-inhibit-control
      - unity7 # Possibly unneeded
      - wayland
      - x11

parts:
  # https://ubuntu.com/frame/docs/24/how-to/use-snap-graphics/
  gpu-2404:
    after: [cctv-viewer]
    plugin: dump
    source: https://github.com/canonical/gpu-snap.git
    override-prime: |
      craftctl default
      ${CRAFT_PART_SRC}/bin/gpu-2404-cleanup mesa-2404
      # Workaround for https://bugs.launchpad.net/snapd/+bug/2055273
      mkdir -p "${CRAFT_PRIME}/gpu-2404"
    prime:
      - bin/gpu-2404-wrapper

  desktop-qt5:
    plugin: dump
    source: snap/local
    stage-packages:
      - libxkbcommon0
      - fonts-ubuntu
      - dmz-cursor-theme
      - adwaita-icon-theme
      - shared-mime-info
      # - libqt5gui5
      - libgdk-pixbuf2.0-0
      - libqt5svg5 # For loading icon themes which are svg
      - locales-all
      - xdg-user-dirs
      - fcitx5-frontend-qt5
    organize:
      desktop-launch: bin/

  qt5-gtk-platform:
    plugin: nil
    stage-packages:
      - qt5-gtk-platformtheme

  qt5-kde-platform:
    plugin: nil
    stage-packages:
      - plasma-integration # KDE Plasma Keyboard Shortcuts support

  cctv-viewer:
    after: [desktop-qt5, qt5-gtk-platform, qt5-kde-platform]
    plugin: cmake
    cmake-parameters:
      - -DPACKAGER=SNAP
      - -DCMAKE_BUILD_TYPE=Release
    source: .
    override-pull: |
      craftctl default
      # Point icon to the correct location
      sed -i.bak -e 's|Icon=cctv-viewer|Icon=/usr/share/pixmaps/cctv-viewer.svg|g' cctv-viewer.desktop
    build-packages:
      - build-essential
      - libva-dev
      - libglx-dev
      - libegl-dev
      - libgles-dev
      - libdrm-dev
      - libavformat-dev
      - libavcodec-dev
      - libavutil-dev
      - libswscale-dev
      - libswresample-dev
      - libavdevice-dev
      - libavfilter-dev
      - qtdeclarative5-dev
      - qtmultimedia5-dev
      - qttools5-dev
      - libgtest-dev
      - git
      - pkg-config
    stage-packages:
      # Debian package dependencies (TODO: Check and update)
      - libavcodec60
      - libavdevice60
      - libavfilter9
      - libavformat60
      - libavutil58
      - libc6
      - libgcc-s1
      - libgl1
      - libqt5core5t64
      - libqt5gui5t64
      - libqt5multimedia5
      - libqt5qmlmodels5
      - libqt5quick5
      - libqt5quickcontrols2-5
      - libstdc++6
      - libswresample4
      - libswscale7
      - libva-x11-2
      - libva2
      - libx11-6
      - libqt5multimedia5-plugins
      - qtwayland5
      - qml-module-qtquick-layouts
      - qml-module-qtqml-models2
      - qml-module-qtquick-controls
      - qml-module-qtquick-controls2
      - qml-module-qtquick-window2
      - qml-module-qtquick-dialogs
      - qml-module-qt-labs-settings
      - qml-module-qtmultimedia
      # For Wayland and DRM:
      - libdrm2
      - libva-drm2
      - libva-wayland2
      - libvdpau1
      - va-driver-all
    organize:
      usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/blas/*: usr/lib/
      usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/lapack/*: usr/lib/
      usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/pulseaudio/*: usr/lib/
